mod_2/code-review-practice/config/routes.rb
Rails.application.routes.draw do
  resources :patients, only: [:index, :show, :new, :create]
  resources :doctors, only: [:index, :show]
end

mod_2/code-review-practice/app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :patients
end

mod_2/code-review-practice/app/models/patient.rb
class Patient < ApplicationRecord
    belongs_to :doctor
    validates :name, length: { minimum:5 }
    validates :age, numericality: {less_than: 50}
end

mod_2/code-review-practice/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
    def index
        @doctors = Doctor.all
    end
    def show 
        @doctor = Doctor.find(params[:id])
    end
end

mod_2/code-review-practice/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    def index
        @patients = Patient.all
    end
    def show
        @patient = Patient.find(params[:id])
        @doctor = @patient.doctor
    end
    def new
        @patient = Patient.new
    end

    def create
        @patient = Patient.create(patient_params)
        # byebug
        if @patient.valid?
            redirect_to patient_path(@patient)
        else
            render :new
        end
    end
    private
    def patient_params
        params.require(:patient).permit(:name, :age, :doctor_id)
    end
end

mod_2/code-review-practice/app/helpers/doctors_helper.rb
module DoctorsHelper
end

mod_2/code-review-practice/app/helpers/patients_helper.rb
module PatientsHelper
end

mod_2/code-review-practice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

mod_2/code-review-practice/app/views/patients/index.html.erb
<h1> All Patients! </h1>

<ul>
<% @patients.each do |patient|%>
    <li><%=link_to patient.name, patient%></li>
<%end%>
</ul>

mod_2/code-review-practice/app/views/patients/new.html.erb
<% if @patient.errors.any? %>
    <% @patient.errors.full_messages.each do |fm|%>
        <p> <%= fm %> </p>
    <% end%>
<% end %>

<%= form_for @patient do |f|%>
    <%= f.label :name %>
    <%= f.text_field :name%>
    <%= f.label :age %>
    <%= f.number_field :age%>
    <%= f.label :doctor %>
    <%= f.collection_select :doctor_id, Doctor.all, :id, :name%>
    <%= f.submit%>
<% end %>

mod_2/code-review-practice/app/views/patients/show.html.erb
<p>Name: <%= @patient.name%></p>
<p>Age : <%= @patient.age%></p>
<p>Doctor : <%=link_to @doctor.name, doctor_path(@doctor)%></p>